version: 2
updates:
- package-ecosystem: bundler
  directory: "/"
  schedule:
    interval: weekly
    time: "13:00"
    timezone: Europe/Brussels
  open-pull-requests-limit: 99
  commit-message:
    prefix: ""
  labels:
    - "dependencies"
- package-ecosystem: npm
  directory: "/"
  schedule:
    interval: weekly
    time: "13:00"
    timezone: Europe/Brussels
  open-pull-requests-limit: 99
  commit-message:
    prefix: ""
  labels:
    - "dependencies"
- package-ecosystem: github-actions
  directory: "/"
  schedule:
    interval: weekly
    time: "13:00"
    timezone: Europe/Brussels
  open-pull-requests-limit: 99
  commit-message:
    prefix: ""
  labels:
    - "dependencies"
