name: Deploy Naos

on:
  workflow_call:
  workflow_dispatch:
  pull_request:
    types:
      - labeled

concurrency: deploy-naos

jobs:
  deploy:
    if: ${{ github.event.action != 'labeled' || (github.event.action == 'labeled' && github.event.label.name == 'deploy naos') }}
    environment:
      name: naos
      url: https://naos.ugent.be
    runs-on: ubuntu-latest
    steps:
    - name: Install SSH key
      uses: shimataro/ssh-key-action@v2
      with:
        key: ${{ secrets.MESTRA_KEY }}
        known_hosts: ${{ secrets.MESTRA_HOST }}
    - name: Run deploy
      run: |
        echo "deploy naos $GITHUB_SHA" | ssh -p 4840 dodona@mestra.ugent.be
    - name: Remove deploy label
      if: github.event.action == 'labeled'
      uses: buildsville/add-remove-label@v2.0.1
      with:
        token: ${{secrets.GITHUB_TOKEN}}
        label: deploy naos
        type: remove
    - name: Get tag name
      id: tag_name
      run: echo "tag_name=$(date +'%Y.%m.%d-%H:%M')" >> "$GITHUB_ENV"
    - uses: actions/checkout@v3
      with:
        fetch-depth: 0
    - name: Create Sentry release
      uses: getsentry/action-release@v1
      env:
        SENTRY_AUTH_TOKEN: ${{ secrets.SENTRY_AUTH_TOKEN }}
        SENTRY_ORG: dodona
        SENTRY_PROJECT: dodona-frontend
      with:
        environment: staging
        version: ${{ env.tag_name }}
