name: Deploy production

# Queue the deploy, but don't cancel any currently running workflows
concurrency: deploy-production-safe

on:
  workflow_dispatch:

jobs:
  run-tests:
    uses: ./.github/workflows/test.yml
  run-linting:
    uses: ./.github/workflows/lint.yml
  deploy-naos:
    uses: ./.github/workflows/deploy-naos.yml
  deploy-production:
    needs: [run-tests, deploy-naos, run-linting]
    uses: ./.github/workflows/deploy-production.yml
