name: Deploy production unchecked

# Queue the deploy, but don't cancel any currently running workflows
concurrency: deploy-production

on:
  workflow_call:
  workflow_dispatch:

jobs:
  deploy:
    environment:
      name: production
      url: https://dodona.be
    runs-on: ubuntu-latest
    steps:
    - name: Install SSH key
      uses: shimataro/ssh-key-action@v2
      with:
        key: ${{ secrets.MESTRA_KEY }}
        known_hosts: ${{ secrets.MESTRA_HOST }}
    - name: Run deploy
      run: |
        echo "deploy production $GITHUB_SHA" | ssh -p 4840 dodona@mestra.ugent.be
    - name: Get tag name
      id: tag_name
      run: echo "tag_name=$(TZ='Europe/Brussels' date +'%Y.%m.%d-%H:%M')" >> "$GITHUB_ENV"
    - uses: actions/checkout@v3
      with:
        fetch-depth: 0
    - name: Create Sentry release
      uses: getsentry/action-release@v1
      env:
        SENTRY_AUTH_TOKEN: ${{ secrets.SENTRY_AUTH_TOKEN }}
        SENTRY_ORG: dodona
        SENTRY_PROJECT: dodona-frontend
      with:
        environment: production
        version: ${{ env.tag_name }}
